import type { BoardView } from '../scene/Camera.js';

type Copy = { title: [string, string]; instruction: [string, string]; result: [string, string]; camera: BoardView };
/** Each pair is English / Chinese. The same language preference as the rest of the app applies. */
export const copy: Record<string, Copy> = {
  role: { title: ['Choose a role', '选择角色'], camera: 'shared', instruction: ['Select Planter below, then confirm. Everyone takes part in a role; its chooser receives a privilege.', '选择下方的种植者，然后确认。所有玩家都参与该阶段，选择角色的人享有特权。'], result: ['You chose Planter. Next, take a corn estate. The lesson follows a prepared path; roles can occur in a different order in a real game.', '你选择了种植者。接下来领取玉米田园。教程使用固定流程，实际游戏的角色顺序可以不同。'] },
  estate: { title: ['Take an estate', '领取田园'], camera: 'estates', instruction: ['Select the highlighted corn estate and confirm. It will need a worker to produce corn.', '选择高亮的玉米田园并确认。田园需要工人才能生产玉米。'], result: ['Corn estate acquired. We now skip the other players’ decisions and move to the building phase.', '已领取玉米田园。现在跳过其他玩家的决策，进入建筑阶段。'] },
  build: { title: ['Build Small Market', '建造小市场'], camera: 'buildings-1', instruction: ['Select Small Market and confirm its price. When staffed, it can earn an extra coin when you trade.', '选择小市场并确认价格。有工人时，它可以在交易中额外赚取一枚金币。'], result: ['Small Market is built. We advance through recruitment to a worker-placement lesson; the other players’ turns are scripted.', '小市场已建成。我们跳转到招募后的工人分配教学；其他玩家的行动由教程安排。'] },
  workers: { title: ['Put workers to work', '分配工人'], camera: 'mine', instruction: ['Move the worker from the fruit estate to corn, then place a pool worker in Small Market. Only the next required object is selectable.', '将水果田园上的工人移到玉米田园，再将池中工人放入小市场。每次只能选择当前需要的对象。'], result: ['Corn and Small Market are staffed. We skip to your Craftsman phase to produce goods.', '玉米田园和小市场已安排工人。现在跳转到你的工匠阶段来生产货物。'] },
  produce: { title: ['Produce goods', '生产货物'], camera: 'mine', instruction: ['Confirm production below. Corn only needs a staffed estate; most other goods also need a staffed processing building. Auto-produce is off for this lesson.', '在下方确认生产。玉米只需要有工人的田园；多数其他货物还需要有工人的加工建筑。教程中已关闭自动生产。'], result: ['You produced one corn. As the Craftsman chooser, you may take one extra produced good.', '你生产了一箱玉米。作为工匠的选择者，你可以再领取一箱已生产的货物。'] },
  bonus: { title: ['Take your privilege', '领取特权奖励'], camera: 'mine', instruction: ['Select corn below and confirm your extra crate.', '选择下方的玉米并确认领取额外货箱。'], result: ['You now have two corn. We advance to trading: sell one and keep the other for shipping.', '你现在有两箱玉米。接下来进入交易：出售一箱，留一箱用于运货。'] },
  trade: { title: ['Trade for coins', '交易换取金币'], camera: 'depot', instruction: ['Select the first corn crate below, then the highlighted trading depot. Small Market adds one coin to corn’s base selling price of zero.', '选择下方第一箱玉米，再选择高亮的交易所。玉米基础售价为零，小市场可额外赚取一枚金币。'], result: ['You earned one coin and kept one corn. We skip to your Captain phase to ship the remaining crate.', '你赚取了一枚金币，还剩一箱玉米。现在跳转到你的船长阶段，运送剩余货箱。'] },
  ship: { title: ['Ship for points', '运货获得分数'], camera: 'boats', instruction: ['Select the remaining corn crate below, then the highlighted ship. Shipping earns points, not coins.', '选择下方剩余的玉米货箱，再选择高亮货船。运货获得分数，而不是金币。'], result: ['You earned two points: one for the corn and one Captain privilege point. Estates + workers make goods; trade earns coins; shipping earns points.', '你获得了两分：玉米一分，船长特权一分。田园加工人生产货物，交易赚取金币，运货获得分数。'] },
};
