// Isolated visual experiment: never imported by the production game.
import * as T from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const holder = document.querySelector<HTMLElement>('#stage')!;
const status = document.querySelector<HTMLElement>('#status')!;
const renderer = new T.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.toneMapping = T.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.1;
holder.append(renderer.domElement);
const scene = new T.Scene(); scene.background = new T.Color('#236c76');
const camera = new T.PerspectiveCamera(40, 1, 0.1, 1000);
const controls = new OrbitControls(camera, renderer.domElement);
controls.maxPolarAngle = Math.PI * 0.47; controls.minDistance = 15; controls.maxDistance = 180;
controls.zoomSpeed = 0.3;
scene.add(new T.HemisphereLight('#fff8e9', '#557378', 2));
const sun = new T.DirectionalLight('#fff3d7', 2.1); sun.position.set(-25, 60, 30); scene.add(sun);
const render = () => renderer.render(scene, camera);
const reset = () => { camera.position.set(0, 55, 40); controls.target.set(0, 0, 0); controls.update(); render(); };
controls.addEventListener('change', render);
new ResizeObserver(() => { renderer.setSize(holder.clientWidth, holder.clientHeight); camera.aspect = holder.clientWidth / holder.clientHeight; camera.updateProjectionMatrix(); render(); }).observe(holder);
reset();
try {
  const texture = await new T.TextureLoader().loadAsync('/art/environment/main-island.webp');
  texture.colorSpace = T.SRGBColorSpace;
  const original = new T.Mesh(new T.PlaneGeometry(64, 32), new T.MeshBasicMaterial({ map: texture, transparent: true, alphaTest: .015 }));
  original.rotation.x = -Math.PI / 2; original.visible = false; scene.add(original);
  const gltf = await new GLTFLoader().loadAsync('/art/meshy-island/Main%20Island.glb');
  const model = gltf.scene;
  const bounds = new T.Box3().setFromObject(model), size = bounds.getSize(new T.Vector3()), center = bounds.getCenter(new T.Vector3());
  const scale = 64 / Math.max(size.x, size.z);
  model.position.set(-center.x, -bounds.min.y, -center.z);
  const scaled = new T.Group(); scaled.add(model); scaled.scale.setScalar(scale);
  const rotation = new T.Group(); rotation.rotation.y = Math.PI; rotation.add(scaled); scene.add(rotation);
  let triangles = 0, meshes = 0;
  model.traverse(o => { if (o instanceof T.Mesh) { meshes++; triangles += (o.geometry.index?.count ?? o.geometry.getAttribute('position').count) / 3; } });
  const report = { triangles, meshes, sourceDimensions: size.toArray(), fittedDimensions: size.clone().multiplyScalar(scale).toArray() };
  console.info('Island geometry', report);
  status.textContent = `${Math.round(triangles).toLocaleString()} triangles · ${meshes} meshes · ${report.fittedDimensions.map(n => n.toFixed(1)).join(' × ')} board units (width / height / depth)`;
  const toggle = (showModel: boolean) => { rotation.visible = showModel; original.visible = !showModel; document.querySelector('#model')!.setAttribute('aria-pressed', String(showModel)); document.querySelector('#image')!.setAttribute('aria-pressed', String(!showModel)); render(); };
  document.querySelector<HTMLButtonElement>('#model')!.onclick = () => toggle(true);
  document.querySelector<HTMLButtonElement>('#image')!.onclick = () => toggle(false);
  document.querySelector<HTMLButtonElement>('#reset')!.onclick = reset;
  document.querySelector<HTMLButtonElement>('#top')!.onclick = () => { camera.position.set(0, 80, .01); controls.target.set(0, 0, 0); controls.update(); render(); };
  document.querySelector<HTMLInputElement>('#relief')!.oninput = e => { scaled.scale.y = scale * Number((e.target as HTMLInputElement).value); render(); };
  document.querySelector<HTMLSelectElement>('#orientation')!.onchange = e => { rotation.rotation.y = Number((e.target as HTMLSelectElement).value) * Math.PI / 180; render(); };
  render();
} catch (e) { status.textContent = 'Island preview unavailable: ' + (e instanceof Error ? e.message : String(e)); }
